name: Build Raw Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Raw Disk Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Bootc image generation can take a lot of disk space.
      # This step frees up space on the GitHub hosted runner.
      - name: Delete unnecessary tools to free up disk space
        run: sudo rm -rf /opt/hostedtoolcache

      - name: Build Bootc Container Image locally
        run: sudo podman build -t localhost/rhs-bootstrapper:latest -f Containerfile .

      - name: Build Raw Disk Image using bootc-image-builder
        run: |
          sudo mkdir -p ./output
          sudo podman run \
            --rm \
            -it \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v ./output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            build \
            --type raw \
            --rootfs xfs \
            localhost/rhs-bootstrapper:latest

      - name: Upload Raw Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rhs-bootstrapper-raw-image
          path: output/image/disk.raw
